import { StyleSheet } from "react-native";

const styles = StyleSheet.create(
    {
        navBar: {
            flex: 1,
            flexDirection: 'row',
            justifyContent: 'center',
            alignContent: 'center',
            alignItems: 'stretch',
            padding: 3,
            borderRadius: 6,
            borderColor: 'lightgrey',
        },
        screen: {
            flex: 1,
            flexDirection:'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginLeft: 10,
            marginRight:15,
        },
        container:{
            flex: 1,
            flexDirection: 'row-reverse',
            justifyContent: 'flex-start',
            alignItems: 'center',
            padding: 10,
            width: 50,
            borderRadius: 8,
            borderWidth: 1,
            marginTop: 5,
            columnGap: 10,
            marginRight: 15,
            borderColor: 'lightgrey',
            backgroundColor: '#fff',
        },
        bar: {
            flexDirection: 'column',
            alignItems: 'stretch',
            justifyContent: 'center',
            marginTop: 15,
            marginLeft: 10,
            marginRight: 25,
            borderRadius: 8,
            height: 170,
            padding: 5,
            overflow: 'hidden',
            backgroundColor: '#fff',
            borderWidth: 1,
            borderColor: 'lightgrey',
        },
        msv: {
            flex: 1,
            flexDirection: 'row',
            justifyContent: 'space-between',
        },
        ki: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            alignContent: 'center',
            justifyContent: 'center',
            padding: 10,
            borderWidth: 1,
            borderColor: 'lightgrey',
            borderRadius: 8,
            marginTop: 10,
        },
        gre: {
            width: 10,
            height: 10,
            borderRadius: 5,
            borderWidth: 1,
            marginLeft: 5,
            backgroundColor: 'green',
        },
        green: {
            width: 10,
            height: 10,
            borderRadius: 5,
            borderWidth: 1,
            backgroundColor: 'green',
        },
        red: {
            width: 10,
            height: 10,
            borderRadius: 5,
            borderWidth: 1,
            backgroundColor: 'red'
        },
        orange: {
            width: 10,
            height: 10,
            borderRadius: 5,
            borderWidth: 1,
            backgroundColor: 'orange'
        },
        tea: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginTop: 10,
            marginRight: 10,
            marginLeft: 10,
        },
        ate: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-around',
            marginTop: 10,
            marginRight: 10,
            marginLeft: 10,
        },
        calendar: {
            borderWidth: 1,
            borderColor:'light',
            borderRadius: 5,
            paddingVertical: 4,
            paddingHorizontal: 4,
        },
        nav: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-evenly',
            marginTop: 10,
        },
        row: {
            flex: 1,
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: 15,
            marginLeft: 10,
            marginRight: 25,
            padding: 10,
            borderColor: 'lightgrey',
            borderRadius: 8,
            borderWidth: 1,
        },
        wrap: {
            flexDirection: 'row',
            justifyContent: 'space-around',
            alignItems: 'center',
            width: '100%',
            height: 120,
            paddingHorizontal: 20,
        },
        roll: {
            alignItems: 'center',
            
        },
        itemtext: {
            marginTop: 6, 
            fontWeight: 'bold',
            textAlign: 'center',
        },
        
        circle: {
            justifyContent: 'center',
            alignItems: 'center',
            width: 150,
            height: 150,
            borderRadius: 75,
            borderWidth: 5,
            borderColor: 'lightgray',
            borderRightColor: 'green',
            backgroundColor: 'transparent',
            marginTop: 20,
            marginLeft: 180,
        },
        chek: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            marginTop: 5,
        },
        box: {
            padding: 16,
            borderRadius: 8,
            backgroundColor: 'blue',
            paddingLeft: 100,
            paddingRight: 100,
        },
        cicle: {
            width: 20,
            height: 20,
            borderRadius: 10,
            borderWidth: 1,
            backgroundColor: 'green'
        },
        fully: {
            flexDirection: 'column',
            backgroundColor: '#fff',
            alignItems: 'center',
            justifyContent: 'center',
            height: 400,
            marginTop: 10,
            borderRadius: 8,
        },
        suc: {
            height: 180,
            width: 180,
            borderRadius: 90,
            alignItems: 'center',
            justifyContent: 'center',
        },
        jb: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginTop: 5,
            gap: 5,
            padding: 4,
            borderColor: 'lightgrey',
            borderRadius: 8,
            borderWidth: 1,
            marginLeft: 10,
            marginRight: 10,
        },
        cic: {
           width: 20,
            height: 20,
            borderRadius: 10,
            borderWidth: 1,
            backgroundColor: 'gray' 
        },
        leav: {
            alignItems: 'center',
            justifyContent: 'center',
            padding: 16,
            backgroundColor: '#fff',
        },
        req: {
            flex: 1,
            flexDirection: 'row',
            justifyContent: 'space-evenly',
            padding: 2,
        },
        line: {
            fontSize: 14,
            color: 'blue',
            borderBottomColor: 'blue',
            borderBottomWidth: 2,
            paddingBottom: 5,
        },
        cas: {
            flex: 14,
            flexDirection: 'column',
            alignItems: 'stretch',
            justifyContent: 'center',
            marginTop: 15,
            marginLeft: 10,
            marginRight: 25,
            borderRadius: 10,
            height: 300,
            padding: -1,
            gap:10,
        },
        saul: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: 5,
            borderRadius: 10,
            borderWidth: 1,
            borderColor: 'lightgrey',
        },
        but: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'blue',
        color: '#fff',
    },
    dim: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#00000050',
        zIndex: 1,
    },
    wifi: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginRight: 30,
        marginLeft: 50,
    },
    in: {
        flexDirection: 'column',
        backgroundColor: '#fff',
        height: 600,
        marginTop: 10,
        borderRadius: 8,
    },
    date: {
            textAlign: 'left',
            marginTop: 10,
            marginLeft: 10,
            fontWeight: 'bold',
        },
        tim: {
            textAlign: 'left',
            marginTop: 10,
            marginLeft: 10,
            fontWeight: 'bold',
        },
        locate: {
            textAlign: 'left',
            marginTop: 10,
            marginLeft: 20,
            fontWeight: 'bold',
        },
        num: {
            textAlign: 'left',
            marginLeft: 20,
            marginTop: 10,
            fontWeight: 'bold',
        },
        datim: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginLeft: 10,
            marginRight: 20,
        },
        put: {
            borderColor: 'lightgrey',
            borderWidth: 2,
            padding: 2,
            marginTop: 5,
            borderRadius: 6,
        },
    input: {
            borderColor: 'lightgrey',
            borderWidth: 2,
            padding: 10,
            marginTop: 5,
            borderRadius: 10,
            marginLeft: 10,
            marginRight: 20,
        },
        start: {
            textAlign: 'left',
            marginTop: 10,
            marginLeft: 10,
            fontWeight: 'bold',
        },
        stop: {
            textAlign: 'left',
            marginTop: 10,
            marginLeft: 10,
            fontWeight: 'bold',
        },
        reason: {
            textAlign: 'left',
            marginTop: 10,
            marginLeft: 10,
            fontWeight: 'bold',
        },
        doc: {
            textAlign: 'left',
            marginTop: 10,
            marginLeft: 10,
            fontWeight: 'bold',
        },
        wide: {
            borderColor: 'lightgrey',
            borderWidth: 2,
            padding: 25,
            marginTop: 5,
            borderRadius: 10,
            marginLeft: 10,
            marginRight: 35,
        },
        inside: {
            flexDirection: 'row-reverse',
            alignItems: 'center',
            paddingHorizontal: 10,
            marginVertical: 10,
        },
        jos: {
            flex: 1,
            paddingVertical: 12,
            borderColor: 'lightgrey',
            borderWidth: 2,
            padding: 10,
            marginTop: 5,
            borderRadius: 10,
            marginRight: 5,
        },
        sac: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginRight: 220,
            marginLeft: 15,
            marginTop: 15,
        },
        checkbox: {
            backgroundColor: 'lightgreen',
            padding: 3,
        },
        ground : {
            flex: 1,
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
        },
        
        
   }
)


export default styles;