import { StyleSheet } from "react-native";



const styles = StyleSheet.create (
    {
        wifi: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginRight: 30,
        marginLeft: 50,
    },
        leav: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginTop: 10,
            marginRight: 10,
            marginLeft: 10,
        },
        req: {
            flex: 1,
            flexDirection: 'row',
            justifyContent: 'space-evenly',
            padding: 2,
            marginTop: 10,
        },
        line: {
            fontSize: 14,
            color: 'blue',
            borderBottomColor: 'blue',
            borderBottomWidth: 2,
            paddingBottom: 5,
        },
        con: {
           
        },
        scrollcon: {
             flex: 1,
             flexDirection: 'row',
            paddingTop: 20,
            paddingHorizontal: 16,
            gap: 10,
        },
        hor: {
            flexWrap: 'wrap',
            width: 150,
            height: 150,
            justifyContent: 'center',
            padding: 3,
            paddingVertical: 5,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: 'lightgrey',
        },
        cas: {
            flex: 14,
            flexDirection: 'column',
            alignItems: 'stretch',
            justifyContent: 'center',
            marginTop: 10,
            marginLeft: 15,
            marginRight: 25,
            borderRadius: 8,
            height: 300,
            padding: -1,
            gap:10,
        },
        saul: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: 5,
            borderRadius: 5,
            borderWidth: 1,
            borderColor: 'lightgrey',
            
        },
        but: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'blue',
    },
    per: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        marginTop: 15,
    },
    rate: {
        flexDirection: 'column',
        height: 350,
        marginTop: 10,
        marginLeft: 10,
        marginRight: 15,
        padding: 1,
        borderWidth: 1,
        borderRadius: 8,
        borderColor: 'lightgrey',
    },
    exc: {
        flexWrap: 'wrap',
        justifyContent: 'center',
        alignItems: 'center',
        width: 120,
        height: 120,
        borderRadius: 60,
        borderWidth: 5,
        borderColor: 'lightgray',
        borderLeftColor: 'green',
        borderTopColor: 'green',
        backgroundColor: 'transparent',
        borderBottomColor: 'transparent',
        marginTop: 20,
        marginLeft: 180,
    },
    go: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 1,
        borderWidth: 1,
        borderRadius: 12,
        borderColor: 'lightgrey',
        marginRight: 10,
        marginTop: 15,
        marginLeft: 15,
    },
    rev: {
        flexDirection: 'column',
        height: 160,
        marginTop: 20,
        marginLeft: 10,
        marginRight: 15,
        padding: 1,
        borderWidth: 1,
        borderRadius: 8,
        borderColor: 'lightgrey',
    },
    msv: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginLeft: 15,
        marginRight: 15,
        marginTop: 10,
        },
        mid: {
            
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: 3,
            borderWidth: 1,
            borderRadius: 10,
            borderColor: 'lightgrey',
            marginTop: 10,
            marginLeft: 10,
            marginRight: 10,
        },
        up: {
            borderRadius: 10,
            backgroundColor: 'lightblue',
            padding: 3,
            marginRight: 15,
        },
        com:{
            borderRadius: 10,
            backgroundColor: 'lightgreen',
            padding: 1,
            marginRight: 15,
        },
        overall: {
            flex: 1,
            flexDirection: 'row',
            justifyContent: 'space-evenly',
            alignItems: 'center',
        },

        complete: {
        width: 90,
        height: 90,
        borderRadius: 45,
        borderWidth: 5,
        borderColor: 'lightgray',
        borderLeftColor: 'green',
        borderTopColor: 'green',
        backgroundColor: 'transparent',
        borderBottomColor: 'transparent',
        marginTop: 10,
        },
        pro: {
            flexWrap: 'wrap',
            flexDirection: 'column',
            alignItems: 'center',
        },
        ball: {
            width: 10,
            height: 10,
            borderRadius: 5,
            borderWidth: 1,
            backgroundColor: 'green',
        },
        smallball: {
            width: 10,
            height: 10,
            borderRadius: 5,
            borderWidth: 1,
            backgroundColor: 'blue',
        },
        handball: {
            width: 10,
            height: 10,
            borderRadius: 5,
            borderWidth: 1,
            backgroundColor: 'gray',
        },

        viewall: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
        marginLeft: 20,
        marginRight: 50,
        },
        reseach: {
        flexDirection: 'column',
        height: 200,
        marginTop: 20,
        marginLeft: 10,
        marginRight: 15,
        padding: 1,
        borderRadius: 8,
        borderColor: 'lightgrey',
        },
        user: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: 3,
            borderWidth: 1,
            borderRadius: 10,
            borderColor: 'lightgrey',
            marginTop: 10,
            marginLeft: 10,
            marginRight: 10,
        },
        percent: {
            width:20,
            height: 15,
            borderWidth: 1,
            backgroundColor: 'lightgray',
            marginRight: 5,
            marginTop: 3,
            borderRadius: 5,
        },
        fed: {
            flexDirection: 'column',
            height: 200,
            borderWidth: 1,
            borderColor: 'lightgrey',
            borderRadius: 8,
            marginRight: 25,
            marginLeft: 20,
            marginTop: 10,
            gap: 10,
        },
         all: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginLeft: 10,
            marginRight: 15,
         },
         josh: {
            flexDirection: 'row',
            alignItems: 'center',
            padding: 2,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: 'lightgrey',
         },
         man: {
            borderRadius: 8,
            backgroundColor: 'lightblue',
            padding: 3,
            borderWidth: 1,
            marginLeft: 10,
            fontSize: 8,
         },
         icon: {
            marginLeft: 10,
         },
         star: {
            color: 'green',
            backgroundColor: 'lightgreen',
            padding: 1, 
            borderRadius: 8,
         },
         my: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            marginTop: 10,
            padding: 10,
            borderRadius: 10,
            borderWidth: 1,
            borderColor: 'lightgrey',
            marginLeft: 15,
            marginRight: 20,
         },
         ima: {
            marginLeft: 10,
         },
         emp: {
            color: 'blue',
            backgroundColor: 'lightblue',
            padding: 3,
            borderRadius: 6,
            marginLeft: 100,
         },
         time: {
            color: 'green',
            backgroundColor: 'lightgreen',
            padding: 3,
            borderRadius: 6,
            marginLeft: 150,
         },
         info: {
            flexDirection: 'column',
            height: 150,
            padding: 10,
            borderRadius: 10,
            borderWidth: 1,
            borderColor: 'lightgrey',
            marginLeft: 15,
            marginRight: 20,
            marginTop: 10,
            gap: 9,

         },
         mail: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: 1,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: 'lightgrey',
         },
         workinfo: {
            flexDirection: 'column',
            height: 200,
            padding: 10,
            borderRadius: 10,
            borderWidth: 1,
            borderColor: 'lightgrey',
            marginLeft: 15,
            marginRight: 20,
            marginTop: 10,
            gap: 9,
         },
         log: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            padding: 3,
            borderRadius: 12,
            backgroundColor: 'red',
            marginTop: 15,
            marginLeft: 30,
            marginRight: 30,
         },
         feedback: {
            flexDirection: 'column',
            height: 600,
            borderWidth: 1,
            borderRadius: 8,
            marginRight: 25,
            marginLeft: 20,
            marginTop: 15,
            gap: 10,
            borderColor: 'lightgrey',
         },
    }
)

export default styles;